name: IndexNow
on:
  push:
    branches:
      - main  # Or 'master' if your repo uses master

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Bing IndexNow
        run: |
          curl -I "https://www.bing.com/indexnow?url=https://viewgold.vercel.app/&key=5eb354c570e44005a618cbf7b0d2dad3"
      
      - name: Ping Yandex IndexNow
        run: |
          curl -I "https://yandex.com/indexnow?url=https://viewgold.vercel.app/&key=5eb354c570e44005a618cbf7b0d2dad3"