name: IndexNow
on:
  push:
    branches:
      - main  # Make sure this matches your branch name (main or master)

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Bing IndexNow
        run: |
          # We use -v to see the response, but remove -I so it sends a GET request
          curl "https://www.bing.com/indexnow?url=https://www.goldview.tech/&key=5eb354c570e44005a618cbf7b0d2dad3"
      
      - name: Ping Yandex IndexNow
        run: |
          curl "https://yandex.com/indexnow?url=https://www.goldview.tech/&key=5eb354c570e44005a618cbf7b0d2dad3"